Blog_Clone_Project/urls.py
from django.contrib import admin
# from django.contrib import admin
from django.urls import path, include
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='index'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/',views.LogOutView.as_view(), name='logout'),
    path('register/',views.UserCreateView.as_view(), name='register'),

    path('post/',include('main_app.urls')),
]

main_app/urls.py
from django.urls import path

from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('create/',views.PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/drafts',views.DraftsListView.as_view(), name='drafts'),
    path('<int:pk>',views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/publish', views.publish_post, name='publish_post'),
    path('<int:pk>/edit', views.PostUpdateView.as_view(), name='update_post'),
    path('<int:pk>/delete', views.PostDeleteView.as_view(), name='delete_post'),
    path('<int:post_pk>/add-comment', views.CommentOnPostCreateView.as_view(), name='add_comment'),
]

main_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.



class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from main_app.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email','password1','password2')

main_app/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.messages.api import success
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, FormView, CreateView, DetailView, UpdateView, DeleteView

from main_app.forms import PostForm, CustomUserCreationForm
from main_app.models import *

# Create your views here.


class HomePageView(View):
    template_name = 'main_app/index.html'
    def get(self, request):
        context = dict()
        context['posts'] = Post.objects.filter(is_published=True)
        context['user'] = request.user
        return render(request,self.template_name, context)

class LoginFormView(FormView):
    template_name = 'main_app/login.html'
    form_class = AuthenticationForm
    success_url = '/'
    def form_valid(self, form):
        login(self.request, form.get_user())
        return redirect(self.success_url)


class LogOutView(View):
    def get(self,request):
        logout(request)
        return redirect('/')

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'main_app/post_form.html'

    def get_success_url(self):
        return reverse_lazy('main_app:post_detail',kwargs={'pk':self.object.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DraftsListView(ListView):
    model = Post
    context_object_name = 'drafts'
    template_name = 'main_app/drafts.html'
    def get_queryset(self):
        return Post.objects.filter(is_published=False, author=self.request.user)


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['comments'] = Comment.objects.filter(post=self.get_object())
        return context

class PostUpdateView(UpdateView):
    model = Post
    template_name = 'main_app/post_form.html'
    fields = ('title','content')

    def get_success_url(self):
        return reverse_lazy('main_app:post_detail',kwargs={'pk':self.object.pk})

class PostDeleteView(DeleteView):
    model=Post
    success_url = reverse_lazy('index')

def publish_post(request,pk):
    post = Post.objects.get(pk=pk)
    post.is_published = True
    post.save()
    return redirect('main_app:post_detail', pk=post.pk)


class CommentOnPostCreateView(CreateView):
    model = Comment
    fields= ('content',)
    success_url = '/'
    template_name = 'main_app/add_comment.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = Post.objects.get(pk=self.kwargs['post_pk'])
        form.save()
        return redirect('main_app:post_detail', pk=self.kwargs['post_pk'])


class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'main_app/user_form.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        print(form.cleaned_data)
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.success_url)

templates/main_app/add_comment.html
{% extends 'main_app/base.html' %}

{% block title %}
    Add Comment
{% endblock %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Comment">
    </form>
{% endblock %}

templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base_styles.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>

    <nav>
        <div class="container">
            <div><a href="{% url 'index' %}">My Tech blog</a></div>
            <div><a>About</a></div>
            <div><a>Github</a></div>
            <div><a>LinkedIn</a></div>
        </div>
        <div class="container">
            {% if user.is_authenticated %}

                <div><a href="{% url 'main_app:create_post' %}">New Post</a></div>
                <div><a href="{% url 'main_app:drafts' pk=user.pk%}">Drafts</a></div>
                <div><a href="{% url 'logout' %}">Log out</a></div>
                <div><a></a></div>
            {% else %}
                <div><a href="{% url 'login' %}">LOGIN</a></div>
                <div><a href="{% url 'register' %}">Register</a></div>
            {% endif %}
        </div>

    </nav>
    <main>
        {% block main %}
        {% endblock %}
    </main>
    <footer>
        <div>
            Made by: Velislav Shopov
        </div>
    </footer>
</body>
</html>

templates/main_app/drafts.html
{% extends 'main_app/base.html' %}

{% block title %}
    Drafts
{% endblock %}

{% block main %}
    {% for draft in drafts %}
        <div>
            <h1><a href="{% url 'main_app:post_detail' pk=draft.pk%}">{{ draft.title }}</a></h1>
            <p>{{ draft.date_posted }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/main_app/index.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/index_styles.css' %}">
{% endblock %}


{% block main %}
    <section>
        {% for post in posts %}
            <div class="post_container">
                <h1><a href="{% url 'main_app:post_detail' pk=post.pk%}">{{ post.title }}</a></h1>
                <p>{{ post.date_posted }}</p>
                <p>Comments: {{ post.comments.count }}</p>
            </div>
        {% endfor %}
    </section>
{% endblock %}

templates/main_app/login.html
{% extends 'main_app/base.html' %}

{% block title %}
    Login
{% endblock %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

templates/main_app/post_detail.html
{% extends 'main_app/base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block main %}
    <h1>{{ post.title }}</h1>
    
    
    {% if not post.is_published and post.author == user%}
        <form method="post" action="{% url 'main_app:publish_post' pk=post.pk%}">
            {% csrf_token %}
            <input type="submit" value="Publish">
        </form>
    {% endif %}
    
    
    <p>{{ post.content }}</p>
    
    
    {% if post.author == user %}
        <form method="post" action="{% url 'main_app:update_post' pk=post.pk%}">
            {% csrf_token %}
            <input type="submit" value="Edit">
        </form>
        <form method="post" action="{% url 'main_app:delete_post' pk=post.pk %}">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
    {% endif %}
    
    
    {% if post.is_published %}
        <h3>Comments: {{ comments.count }}</h3>
        {% if comments %}
            {% for comment in comments %}
                <p>{{ comment.author }}: {{ comment.content }}</p>
            {% endfor %}
        {% endif %}
        <a href="{% url 'main_app:add_comment' post_pk=post.pk%}">
            <button>Add Comment</button>
        </a>
        
    {% endif %}
    
    
{% endblock %}

templates/main_app/post_form.html
{% extends 'main_app/base.html' %}

{% block title %}
    Create Post
{% endblock %}

{% block main %}
    
    {% if form.instance.pk %}
        <form method="post">
            {% csrf_token %}
            <label for="id_title">Title:</label>
            <input type="text" name="title" id="id_title" value="{{ post.title }}">
            
                <label for="id_content">Content:</label>
            <textarea name="content" id="id_content">{{ post.content }}</textarea>
            <input type="submit" value="Update">
        </form>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    {% endif %}
{% endblock %}

templates/main_app/user_form.html
{% extends 'main_app/base.html' %}

{% block title %}
    Register
{% endblock %}


{% block main %}
    <form method="post">
        {% csrf_token %}
    <div>
        <label for="id_username">Username:</label>
        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" aria-describedby="id_username_helptext" id="id_username">
    </div>
    <div>
        <label for="id_email">Email address:</label>
        <input type="email" name="email" maxlength="254" id="id_email">
    </div>
    <div>
        <label for="id_password1">Password:</label>
        <input type="password" name="password1" autocomplete="new-password" required="" aria-describedby="id_password1_helptext" id="id_password1">
    </div>
    <div>
        <label for="id_password2">Password confirmation:</label>
        <input type="password" name="password2" autocomplete="new-password" required="" aria-describedby="id_password2_helptext" id="id_password2">
    </div>
        <input type="submit" value="Register">
    </form>
{% endblock %}